### ISSUE TITLE
Fetch new profile data after update profile

### ISSUE THREAD

**Issue by alexanderbryanw** [C22-PS001-Capstone/Vee-Mobile#26]
After dismiss the dialog from update data, not getting new data about updated first name and lastname. Still showing old data. Must logout and login again. 
![image](https://user-images.githubusercontent.com/90922239/169855224-2964ab95-268f-4184-b3b0-c45347389b63.png)

**Comment by ppabcd** [comment]
You can call to get user detail using the saved token in the database.
After receiving new user data, you can update it on the local database.
